[package]
name = "app_state"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.10"

# My local modules
timestamp_tools = { path = "../timestamp_tools" }
database_ops = { path = "../database_ops" }
