[package]
name = "trading_app"
version = "0.1.0"
edition = "2024"

[dependencies]
database_ops = { path = "crates/database_ops" }   
bars = { path = "crates/bars" }   
indicators = { path = "crates/indicators" }   
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
toml = "0.9.10"
tokio = { version = "1.48.0", features = ["full"] }

[workspace]
members = [
  "crates/bars",
  "crates/database_ops", 
  "crates/indicators",
  "crates/timestamp_tools"
]

