[package]
name = "timestamp_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["clock", "std"] }
num-traits = "0.2.19"
sqlx = { version = "0.8.6", features = ["bigdecimal"]}


