[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["postgres"] }

# My modules 
app_core = { path = "../app_core" }   
ratatui = "0.30.0"

